import { GENERATED_POSTS } from '@/lib/blogPosts.generated'

export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  category: string
  readMinutes: number
  publishedAt: string
  content: string[]
}

const STATIC_POSTS: BlogPost[] = [
  {
    slug: 'subir-score-credito-90-dias',
    title: 'Como subir tu score de credito en 90 dias',
    excerpt: 'Plan simple para mejorar tu puntaje sin pagar "credit repair".',
    category: 'Credito',
    readMinutes: 6,
    publishedAt: '2026-05-01',
    content: [
      'Empieza por pagar a tiempo todas tus cuentas activas. Un pago tarde puede tumbar muchos puntos.',
      'Baja la utilizacion de tus tarjetas a menos del 30%, idealmente 10%.',
      'No cierres tarjetas viejas si no tienen cuota anual alta: la antiguedad ayuda al score.',
    ],
  },
  {
    slug: 'evitar-estafas-dealer-autos',
    title: 'Como evitar estafas del dealer al comprar carro',
    excerpt: 'Senales de alerta para no aceptar tasas infladas.',
    category: 'Carro',
    readMinutes: 5,
    publishedAt: '2026-05-02',
    content: [
      'Llega con preaprobacion del banco para comparar la tasa real.',
      'Pide la hoja de terminos completa antes de firmar.',
      'Nunca aceptes "extras" en mensualidad sin ver el costo total.',
    ],
  },
  {
    slug: 'hoa-derechos-inquilino-texas',
    title: 'HOA e inquilinos: lo que si puedes reclamar en Texas',
    excerpt: 'Guia rapida de derechos basicos frente a cobros injustos.',
    category: 'Vivienda',
    readMinutes: 7,
    publishedAt: '2026-05-03',
    content: [
      'Guarda todo por escrito: avisos, multas, y respuestas.',
      'Revisa reglas del HOA y leyes estatales para saber si el cobro aplica.',
      'Si hay abuso, busca ayuda legal comunitaria con evidencia organizada.',
    ],
  },
  {
    slug: 'itin-y-taxes-errores-caros',
    title: 'ITIN y taxes: 5 errores que te cuestan miles',
    excerpt: 'Errores comunes al declarar y como prevenirlos.',
    category: 'Taxes',
    readMinutes: 8,
    publishedAt: '2026-05-04',
    content: [
      'No mezcles ingresos personales y de negocio sin registro claro.',
      'Verifica dependientes y documentos antes de enviar.',
      'Si corriges tarde, puedes perder creditos importantes.',
    ],
  },
  {
    slug: 'remesas-impuesto-2026-como-ahorrar',
    title: 'Impuesto de remesas 2026: como pagar menos legalmente',
    excerpt: 'Opciones practicas para reducir comisiones e impuesto.',
    category: 'Remesas',
    readMinutes: 6,
    publishedAt: '2026-05-05',
    content: [
      'Compara proveedores por costo total, no solo por tipo de cambio.',
      'Evita envios en efectivo cuando exista alternativa digital segura.',
      'Consolida envios para reducir frecuencia de comisiones.',
    ],
  },
  {
    slug: 'prestamos-predatorios-senales',
    title: 'Prestamos predatorios: 7 senales para salir corriendo',
    excerpt: 'Aprende a detectar contratos abusivos antes de firmar.',
    category: 'Prestamos',
    readMinutes: 5,
    publishedAt: '2026-05-06',
    content: [
      'Si no te muestran APR real, es alerta roja.',
      'Si te presionan para firmar hoy mismo, no firmes.',
      'Lee penalidades por atraso y costo total del prestamo.',
    ],
  },
  {
    slug: 'fondo-emergencia-1000-primer-paso',
    title: 'Tu primer fondo de emergencia de $1,000',
    excerpt: 'Metodo en 4 semanas para crear tu colchon.',
    category: 'Emergencias',
    readMinutes: 4,
    publishedAt: '2026-05-07',
    content: [
      'Separa una cuenta solo para emergencias.',
      'Automatiza transferencias pequenas semanales.',
      'Recorta 2 gastos temporales hasta completar la meta.',
    ],
  },
  {
    slug: 'negociar-renta-sin-pelea',
    title: 'Como negociar tu renta sin pelear con el landlord',
    excerpt: 'Guion practico para bajar aumentos injustos.',
    category: 'Vivienda',
    readMinutes: 5,
    publishedAt: '2026-05-08',
    content: [
      'Presenta comparables del area con rentas similares.',
      'Ofrece renovar por mas tiempo a cambio de mejor precio.',
      'Mantente por escrito y con tono profesional.',
    ],
  },
  {
    slug: 'cuenta-bancaria-sin-ssn',
    title: 'Abrir cuenta bancaria sin SSN: pasos reales',
    excerpt: 'Documentos y bancos que suelen aceptar ITIN.',
    category: 'Banco',
    readMinutes: 6,
    publishedAt: '2026-05-09',
    content: [
      'Pregunta por requisitos para ITIN antes de ir en persona.',
      'Lleva identificacion vigente y comprobante de domicilio.',
      'Evita cuentas con cargos ocultos mensuales.',
    ],
  },
  {
    slug: 'disputa-reporte-credito-guia',
    title: 'Como disputar errores en tu reporte de credito',
    excerpt: 'Proceso paso a paso para corregir datos incorrectos.',
    category: 'Credito',
    readMinutes: 7,
    publishedAt: '2026-05-10',
    content: [
      'Descarga tu reporte de las 3 agencias y compara.',
      'Marca cuentas que no reconoces y junta evidencia.',
      'Envia disputa por escrito y guarda numero de caso.',
    ],
  },
  {
    slug: 'salario-justo-calculo-hora',
    title: 'Salario justo: como calcular lo que debes cobrar',
    excerpt: 'Formula simple para saber tu tarifa minima.',
    category: 'Trabajo',
    readMinutes: 5,
    publishedAt: '2026-05-11',
    content: [
      'Incluye transporte, comida y costos de salud en tu calculo.',
      'No compares solo sueldo bruto: mira neto real.',
      'Negocia con datos, no con suposiciones.',
    ],
  },
  {
    slug: 'planes-jubilacion-401k-ira',
    title: '401(k), IRA y Roth: cual te conviene primero',
    excerpt: 'Diferencias claras para decidir hoy.',
    category: 'Jubilacion',
    readMinutes: 6,
    publishedAt: '2026-05-12',
    content: [
      'Si tu empresa hace match, empieza por 401(k).',
      'IRA tradicional reduce impuestos hoy; Roth en retiro.',
      'Aporta constante aunque sea poco al inicio.',
    ],
  },
  {
    slug: 'child-tax-credit-como-reclamar',
    title: 'Child Tax Credit: como reclamarlo bien',
    excerpt: 'Evita perder dinero por errores de documentos.',
    category: 'Taxes',
    readMinutes: 5,
    publishedAt: '2026-05-13',
    content: [
      'Confirma elegibilidad de cada dependiente.',
      'Guarda records de escuela y residencia.',
      'Si te rechazan, apela con evidencia completa.',
    ],
  },
  {
    slug: 'seguro-auto-cobertura-minima',
    title: 'Seguro de auto: cobertura minima que no te deje quebrado',
    excerpt: 'Que cubrir para no pagar de tu bolsillo en un choque.',
    category: 'Carro',
    readMinutes: 6,
    publishedAt: '2026-05-14',
    content: [
      'Lo barato puede salir carisimo en un accidente serio.',
      'Compara deducible con tu capacidad de pago real.',
      'Revisa limites de responsabilidad civil.',
    ],
  },
  {
    slug: 'fraudes-comunes-inmigrantes',
    title: 'Fraudes comunes contra inmigrantes y como defenderte',
    excerpt: 'Patrones de estafa y pasos de proteccion.',
    category: 'Derechos',
    readMinutes: 7,
    publishedAt: '2026-05-15',
    content: [
      'Nunca pagues por promesas de resultados garantizados.',
      'Verifica licencias o certificaciones del proveedor.',
      'Reporta fraudes y guarda todos los recibos.',
    ],
  },
  {
    slug: 'historial-credito-con-itin',
    title: 'Construir historial de credito con ITIN',
    excerpt: 'Estrategia realista para empezar desde cero.',
    category: 'Credito',
    readMinutes: 6,
    publishedAt: '2026-05-16',
    content: [
      'Empieza con tarjeta asegurada y uso bajo.',
      'Paga total o puntual cada mes.',
      'Monitorea score para ajustar estrategia.',
    ],
  },
  {
    slug: 'comprar-casa-primeriza-guia',
    title: 'Primera casa en USA: checklist esencial',
    excerpt: 'Lo minimo que debes preparar antes de aplicar.',
    category: 'Vivienda',
    readMinutes: 8,
    publishedAt: '2026-05-17',
    content: [
      'Define presupuesto con pago mensual comodo.',
      'Evita deudas nuevas 3 a 6 meses antes.',
      'Compara prestamos FHA, convencional y asistencia local.',
    ],
  },
  {
    slug: 'negociar-deuda-medica',
    title: 'Como negociar deuda medica sin destruir tu credito',
    excerpt: 'Pasos para reducir deuda hospitalaria.',
    category: 'Salud financiera',
    readMinutes: 6,
    publishedAt: '2026-05-18',
    content: [
      'Pide itemizacion de cargos y errores facturados.',
      'Solicita programas de charity care si calificas.',
      'Acorda plan de pago por escrito.',
    ],
  },
  {
    slug: 'plan-90-dias-finanzas-familia',
    title: 'Plan de 90 dias para ordenar finanzas familiares',
    excerpt: 'Metodo semanal para cortar fugas de dinero.',
    category: 'Planificacion',
    readMinutes: 7,
    publishedAt: '2026-05-19',
    content: [
      'Semana 1: inventario total de ingresos y gastos.',
      'Semana 2-4: recorte de gastos no esenciales.',
      'Mes 2-3: deuda prioritaria y ahorro automatico.',
    ],
  },
  {
    slug: 'aplicar-subsidios-sin-errores',
    title: 'Como aplicar a subsidios sin errores que te rechacen',
    excerpt: 'Checklist de documentos y tiempos.',
    category: 'Subsidios',
    readMinutes: 5,
    publishedAt: '2026-05-20',
    content: [
      'Completa formularios con la misma informacion en todos.',
      'No omitas ingresos ni miembros del hogar.',
      'Entrega antes de fecha limite y guarda comprobante.',
    ],
  },

  // ─── Los 5 articulos "Evergreen" pilares de El Escudo (supervivencia legal,
  // financiera y burocratica para el hispano). Informacion educativa, no asesoria. ───
  {
    slug: 'como-construir-credito-desde-cero',
    title: 'Como construir credito desde cero en EE.UU.',
    excerpt: 'Sin historial no es "mal credito": es no tener credito. Aqui empiezas tu puntaje desde el dia uno, paso a paso.',
    category: 'Credito',
    readMinutes: 8,
    publishedAt: '2026-06-24',
    content: [
      'En Estados Unidos casi todo se mide por tu credito: rentar, comprar carro, conseguir un buen seguro y hasta algunos trabajos. Si acabas de llegar, no tienes "mal credito": simplemente no existes todavia para el sistema. La buena noticia es que puedes empezar a construirlo desde cero, incluso con ITIN y sin Social Security.',
      'Paso 1 — Consigue una tarjeta asegurada (secured card). Tu depositas un monto (por ejemplo 200 dolares) y ese pasa a ser tu limite. La usas como una tarjeta normal y el banco reporta tus pagos a las agencias de credito. Despues de 6 a 12 meses de buen uso, muchos bancos te devuelven el deposito y te dan una tarjeta normal.',
      'Paso 2 — Usa poco y paga a tiempo. La regla de oro: nunca uses mas del 30% de tu limite (idealmente menos del 10%) y paga el total antes de la fecha de corte. El pago puntual es el factor mas importante de tu puntaje; un solo pago tarde de 30 dias puede costarte muchos puntos.',
      'Paso 3 — Considera ser usuario autorizado. Si un familiar de confianza con buen credito te agrega como usuario autorizado a su tarjeta vieja y bien manejada, ese historial puede empezar a aparecer en tu reporte. No necesitas usar la tarjeta para beneficiarte.',
      'Paso 4 — Suma un tipo de credito distinto cuando ya tengas base. Un credit-builder loan (prestamo para construir credito) o un prestamo pequeno reportado ayudan a tu "mezcla de credito". No abras muchas cuentas de golpe: cada solicitud baja tu puntaje un poco.',
      'Paso 5 — Vigila tu reporte gratis. En annualcreditreport.com puedes revisar tu reporte de las tres agencias (Equifax, Experian, TransUnion) sin pagar. Revisa que no haya errores ni cuentas que no reconozcas, y disputa cualquier dato falso por escrito.',
      'Errores que arruinan el progreso: cerrar tu tarjeta mas antigua (acorta tu historial), pagar solo el minimo arrastrando intereses, y caer en empresas de "credit repair" que cobran por algo que tu puedes hacer gratis. Si alguien te promete borrar deudas reales o subir tu score "garantizado", es estafa.',
      'Con disciplina, en 6 a 12 meses ya tendras un puntaje real y en 18 a 24 meses puedes alcanzar un buen credito. La clave no es ganar mucho dinero: es ser constante y puntual.',
      'Esta guia es informacion educativa general, no asesoria financiera personalizada. Tu situacion puede variar; ante dudas importantes consulta con un asesor financiero o una organizacion comunitaria de confianza.',
    ],
  },
  {
    slug: 'que-hacer-en-un-control-de-trafico',
    title: 'Que hacer en un control de trafico (police stop)',
    excerpt: 'Conocer tus derechos y mantener la calma puede evitar que una parada de trafico se convierta en un problema serio.',
    category: 'Derechos',
    readMinutes: 7,
    publishedAt: '2026-06-24',
    content: [
      'Una parada de trafico pone nervioso a cualquiera, mas si tu ingles no es perfecto o tu estatus migratorio es delicado. Saber como actuar protege tu seguridad y tus derechos. Lo primero: la mayoria de las paradas terminan en nada si mantienes la calma.',
      'Al ver las luces, detente en un lugar seguro a la derecha, apaga el motor, enciende la luz interior si es de noche y baja la ventanilla. Manten las manos visibles sobre el volante. No busques tus documentos hasta que el oficial te lo pida, y avisa antes de moverte: "mis documentos estan en la guantera".',
      'Debes entregar licencia, registro y seguro si te los piden mientras conduces. Eso es obligatorio. Pero tienes derecho a guardar silencio sobre otras cosas: no estas obligado a responder de donde vienes, a donde vas, ni sobre tu lugar de nacimiento o estatus migratorio. Puedes decir, con respeto: "prefiero no responder esa pregunta".',
      'Tienes derecho a negarte a una busqueda (registro) de tu carro si no hay una orden o causa probable. Puedes decir con calma: "no consiento la busqueda". No te resistas fisicamente; solo deja claro de palabra que no das tu consentimiento. La policia decidira, pero tu negativa queda registrada.',
      'No mientas ni muestres documentos falsos: eso si es un delito serio. Es mejor guardar silencio que dar informacion falsa. Si no tienes licencia, entrega lo que tengas y manten la calma.',
      'Pregunta: "soy libre de irme?". Si el oficial dice que si, retirate tranquilo. Si te detienen, no discutas en la calle; el lugar para defenderte es la corte, no el borde de la carretera. Guarda silencio y pide hablar con un abogado.',
      'Despues: anota todo lo que recuerdes (hora, lugar, numero de patrulla, nombre del oficial) y guarda cualquier multa o documento. Si sientes que se violaron tus derechos, busca ayuda legal con esa informacion organizada.',
      'Esta guia es informacion educativa general y no sustituye la asesoria de un abogado. Las leyes varian por estado. Si enfrentas un caso real, busca un abogado o una organizacion de derechos del inmigrante.',
    ],
  },
  {
    slug: 'entender-tu-primer-contrato-de-alquiler',
    title: 'Como entender tu primer contrato de alquiler',
    excerpt: 'Antes de firmar un lease, revisa estas clausulas. Lo que no leas hoy lo pagas caro despues.',
    category: 'Vivienda',
    readMinutes: 8,
    publishedAt: '2026-06-24',
    content: [
      'El contrato de alquiler (lease) es un documento legal que te obliga por meses o anos. Firmarlo sin entenderlo es uno de los errores mas caros del recien llegado. Nunca firmes el mismo dia sin leerlo con calma; pide una copia para revisarla.',
      'Renta y fecha de pago: confirma el monto exacto, el dia limite, el metodo de pago aceptado y el recargo por atraso (late fee). Pregunta si hay periodo de gracia. Todo aumento de renta debe estar por escrito.',
      'Deposito de seguridad (security deposit): cuanto es, en que condiciones te lo devuelven y en cuanto tiempo. Toma fotos y video de TODO el apartamento el dia que te mudas (paredes, pisos, electrodomesticos) y guardalas con fecha: es tu prueba para recuperar el deposito.',
      'Duracion y renovacion: si es por un ano (fixed) o mes a mes (month-to-month). Revisa la penalidad por romper el contrato antes de tiempo (early termination), que puede ser de uno o dos meses de renta. Mira tambien si se renueva solo y con cuanto aviso debes notificar si te vas.',
      'Quien paga que: agua, luz, gas, basura, internet. A veces algunos servicios van incluidos y otros no. Tambien revisa reglas sobre mascotas (pet deposit), visitantes, y si puedes subarrendar.',
      'Reparaciones y mantenimiento: como reportar un dano y en cuanto tiempo deben arreglarlo. El landlord generalmente debe mantener la vivienda habitable (agua, calefaccion, seguridad). Reporta SIEMPRE por escrito (texto o correo) y guarda copia.',
      'Cuidado con clausulas abusivas: que te cobren por cosas vagas, que renuncies a derechos basicos, o acuerdos "de palabra" que no estan en el papel. Si no esta escrito, no existe. Lo que el landlord prometa, que quede en el contrato.',
      'Antes de firmar, asegurate de entender cada pagina; si algo no esta claro, pide que te lo expliquen o busca ayuda para traducirlo. Guarda tu copia firmada en un lugar seguro.',
      'Esta guia es informacion educativa general, no asesoria legal. Las leyes de inquilinos varian por estado y ciudad. Ante un conflicto serio, busca una organizacion de ayuda al inquilino o un abogado.',
    ],
  },
  {
    slug: 'impuestos-basicos-trabajador-independiente',
    title: 'Guia basica de impuestos para trabajadores independientes',
    excerpt: 'Si te pagan en efectivo o con 1099, los impuestos son tu responsabilidad. Asi no te llevas una sorpresa en abril.',
    category: 'Taxes',
    readMinutes: 9,
    publishedAt: '2026-06-24',
    content: [
      'Si trabajas por tu cuenta (contratista, delivery, limpieza, construccion, handyman) y te pagan en efectivo o con un formulario 1099, eres un trabajador independiente ante el IRS. A diferencia del empleado con W-2, a ti no te descuentan impuestos del cheque: tu eres responsable de calcularlos y pagarlos.',
      'Puedes declarar y pagar impuestos aunque no tengas Social Security, usando un ITIN (numero de identificacion de contribuyente). Declarar es importante: crea historial, ayuda en tramites migratorios futuros y te evita problemas legales.',
      'Guarda TODO durante el ano: lo que ganaste y lo que gastaste para trabajar. Una libreta o una app sencilla basta. Sin registros, pagas de mas o cometes errores que te cuestan.',
      'Deducciones (gastos del negocio) que bajan lo que pagas: gasolina y millaje del carro de trabajo, herramientas y materiales, telefono usado para el trabajo, parte de la renta si trabajas desde casa, seguros del negocio. Guarda recibos. Lo personal NO se deduce; no mezcles cuentas personales y de negocio.',
      'El "self-employment tax": ademas del impuesto normal, el independiente paga alrededor del 15.3% por Seguro Social y Medicare (lo que un empleado y su empresa pagan a medias). Por eso conviene apartar entre el 25% y el 30% de cada pago en una cuenta separada para impuestos. Asi no te ahogas en abril.',
      'Pagos estimados trimestrales: si vas a deber mas de cierto monto, el IRS espera que pagues 4 veces al ano (abril, junio, septiembre y enero), no todo de golpe. No hacerlo puede generar multas.',
      'Creditos que mucha gente pierde: el Child Tax Credit por hijos que califican y otros creditos familiares. Confirma la elegibilidad de cada dependiente y guarda pruebas (escuela, residencia).',
      'Errores caros: no declarar por miedo, mezclar dinero personal y de negocio, perder recibos, y caer con "preparadores" que prometen reembolsos enormes o firman cosas que no entiendes. Usa un preparador con credenciales (PTIN) y nunca firmes en blanco.',
      'Esta guia es informacion educativa general, no asesoria fiscal. Cada caso es distinto. Para tu declaracion real, consulta a un contador o preparador de impuestos con licencia.',
    ],
  },
  {
    slug: 'derechos-laborales-basicos-del-trabajador',
    title: 'Derechos laborales basicos del trabajador hispano',
    excerpt: 'Tu estatus migratorio no borra tus derechos en el trabajo. Esto es lo minimo que debes saber para que no te exploten.',
    category: 'Trabajo',
    readMinutes: 8,
    publishedAt: '2026-06-24',
    content: [
      'Un punto clave que muchos no saben: la mayoria de las leyes laborales en EE.UU. protegen a TODOS los trabajadores, sin importar el estatus migratorio. Tienes derecho a que te paguen por tu trabajo aunque te paguen en efectivo o no tengas papeles. El miedo es la herramienta favorita del empleador abusivo.',
      'Salario minimo y horas extra: tienes derecho al menos al salario minimo de tu estado (a menudo mayor que el federal) y, en la mayoria de los empleos, a pago de horas extra (1.5x) por las horas que pasen de 40 a la semana. Que te paguen "por el dia" no elimina ese derecho.',
      'Te deben pagar TODAS las horas trabajadas, incluyendo tiempo de espera, de preparacion o reuniones obligatorias. El robo de salario (no pagar, pagar menos, retener el ultimo cheque) es ilegal y se puede reclamar.',
      'Lleva tu propio registro: anota cada dia las horas que entras y sales y cuanto te pagaron. Si el empleador no lleva records y hay disputa, tu registro vale como evidencia. Guarda mensajes, fotos del horario y cualquier recibo de pago.',
      'Seguridad en el trabajo (OSHA): tienes derecho a un lugar de trabajo seguro, a recibir equipo de proteccion y a reportar condiciones peligrosas sin que te castiguen por ello. Esto aplica sin importar tu estatus.',
      'Represalias: es ilegal que te despidan o amenacen por reclamar tu salario, reportar un peligro o por tu estatus. Amenazar con "llamar a inmigracion" porque reclamas lo tuyo es una forma de represalia que la ley reconoce.',
      'Si te roban el salario o sufres un abuso: junta tu evidencia (horas, pagos, nombres, testigos) y busca ayuda en el Departamento de Trabajo (federal o estatal) o en un centro de trabajadores comunitario. Muchos tramites se pueden hacer sin costo y sin revelar tu estatus.',
      'Cuidado con el "contratista independiente" falso: algunos jefes te llaman independiente (1099) solo para no pagarte horas extra ni proteccion, cuando en realidad controlan tu horario y tu trabajo como a un empleado. Eso puede ser ilegal.',
      'Esta guia es informacion educativa general, no asesoria legal. Las leyes laborales varian por estado. Ante un caso real de abuso, busca un abogado laboral o un centro de derechos del trabajador.',
    ],
  },
]

// Artículos estáticos + generados por IA (SEO long-tail para hispanos)
export const BLOG_POSTS: BlogPost[] = [...STATIC_POSTS, ...GENERATED_POSTS]

export const BLOG_POSTS_BY_SLUG = new Map(BLOG_POSTS.map((post) => [post.slug, post]))
