// Libros y guías del Dr. Figueredo para hispanos en EE.UU. — datos reales
// (portadas + checkout Stripe verificados). Generado desde el catálogo.
export type LibroHispano = {
  title: string; cover: string; spec: string; grupo: string;
  price: number; buyUrl: string; desc: string; specs: string[];
}

export const LIBROS_HISPANO: LibroHispano[] = [
  {
    title: `Seguro de Vida para Familias Latinas`,
    cover: `https://alexanderfigueredo.com/libros/seguro-de-vida-familias-latinas.jpg`,
    spec: `Finanzas · PDF · Manual`,
    grupo: `Finanzas`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/bJe6oB03a8dNbMc45Bd7q0r`,
    desc: `El seguro de vida explicado como un acto de amor para la familia latina en EE.UU.`,
    specs: [`6 mitos que dejan familias desprotegidas`, `Tipos de póliza y cuánto necesitas`, `Aplica para residentes, visa e ITIN`],
  },
  {
    title: `Manual Financiero para el Inmigrante Latino`,
    cover: `https://alexanderfigueredo.com/libros/manual-financiero-inmigrante-latino.jpg`,
    spec: `Finanzas · PDF · Manual · ~29 págs`,
    grupo: `Finanzas`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/9B69ANeY40Ll03udGbd7q0y`,
    desc: `Los 8 escalones para construir tu vida económica en EE.UU. desde cero. Incluye crédito con ITIN.`,
    specs: [`Del primer dólar a la prosperidad`, `SSN/ITIN, banco, crédito, impuestos`, `Comprar casa y planear el futuro`],
  },
  {
    title: `Cómo Funciona el Crédito en EE.UU.`,
    cover: `https://alexanderfigueredo.com/libros/como-funciona-credito-eeuu.jpg`,
    spec: `Finanzas · PDF · Manual`,
    grupo: `Finanzas`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/bJedR303agKj7vW59Fd7q0S`,
    desc: `El manual definitivo para entender, construir y dominar tu crédito en EE.UU.`,
    specs: [`Puntaje FICO y cómo se calcula`, `Cómo leer tu reporte de crédito`, `Subir tu score desde cero — incluso con ITIN`],
  },
  {
    title: `5 Errores que Dañan tu Crédito`,
    cover: `https://alexanderfigueredo.com/libros/5-errores-credito.jpg`,
    spec: `Finanzas · PDF · Guía de prevención`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/dRmbIV4jqeCb4jK7hNd7q0h`,
    desc: `Los 5 errores más comunes que arruinan el crédito y cómo evitarlos desde hoy.`,
    specs: [`Pagos tardíos, uso excesivo y más`, `Los errores más comunes`, `Cómo evitarlos y proteger tu score`],
  },
  {
    title: `Consumismo en EE.UU.: Cómo No Caer en la Trampa`,
    cover: `https://alexanderfigueredo.com/libros/consumismo-como-no-caer.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/7sYdR3aHO0Ll7vW31xd7q0m`,
    desc: `Las trampas del consumismo americano que arruinan a los recién llegados. Protege tu dinero.`,
    specs: [`Trampas que arruinan a los recién llegados`, `Deuda y compras impulsivas`, `Cómo proteger tu dinero`],
  },
  {
    title: `Rentar Casa o Apartamento con Mal Crédito`,
    cover: `https://alexanderfigueredo.com/libros/rentar-con-mal-credito.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/9B6fZbdU051B2bC1Xtd7q0n`,
    desc: `Cómo conseguir vivienda en EE.UU. aunque tu puntaje sea bajo o no tengas historial.`,
    specs: [`Estrategias probadas para conseguir vivienda`, `Cartas, codeudores y depósitos`, `Aunque tengas score bajo`],
  },
  {
    title: `Tarjetas de Crédito: Cómo Usarlas Sin Destruirte`,
    cover: `https://alexanderfigueredo.com/libros/tarjetas-credito-sin-destruirte.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/28E28l03afGf4jK9pVd7q0p`,
    desc: `Cómo usar las tarjetas de crédito para construir historial sin caer en deudas.`,
    specs: [`Elegir, usar y pagar tarjetas`, `Intereses, límites y pagos mínimos`, `Los errores que más hunden a recién llegados`],
  },
  {
    title: `Cómo Arreglar el Mal Crédito Paso a Paso`,
    cover: `https://alexanderfigueredo.com/libros/arreglar-mal-credito-paso-a-paso.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/4gM9ANaHO0LlcQgfOjd7q0I`,
    desc: `El plan claro para subir tu puntaje de crédito en EE.UU. desde cero.`,
    specs: [`Leer tu reporte y disputar errores`, `Bajar tu uso y ponerte al día`, `Reconstruir historial paso a paso`],
  },
  {
    title: `Cómo Comprar Carro Sin Ser Estafado`,
    cover: `https://alexanderfigueredo.com/libros/como-comprar-carro-sin-ser-estafado.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/14A4gt3fm0Ll17y1Xtd7q0K`,
    desc: `Guía para comprar tu carro en EE.UU. sin caer en estafas. Negociar con confianza.`,
    specs: [`Precio justo y financiamiento`, `Trampas del dealer`, `Nuevo o usado, con o sin crédito`],
  },
  {
    title: `La Presión de Enviar Dinero a la Familia`,
    cover: `https://alexanderfigueredo.com/libros/presion-enviar-dinero-familia.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/cNi3cpcPW79J9E46dJd7q0O`,
    desc: `Cómo ayudar a tu familia sin quedarte sin nada. Remesas con equilibrio y sin culpa.`,
    specs: [`Cómo ayudar sin destruirte`, `Límites con amor y sin culpa`, `Protege tu estabilidad económica`],
  },
  {
    title: `Cómo Ahorrar Aunque Ganes Poco`,
    cover: `https://alexanderfigueredo.com/libros/ahorrar-aunque-ganes-poco.jpg`,
    spec: `Finanzas · PDF · Guía`,
    grupo: `Finanzas`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/7sY8wJcPWcu34jK8lRd7q0P`,
    desc: `Guía práctica para empezar a ahorrar aunque el sueldo sea corto. De pequeñas semillas, grandes árboles.`,
    specs: [`Págate a ti primero`, `Regla 50/30/20 explicada`, `Interés compuesto desde pequeños ahorros`],
  },
  {
    title: `Manual del Latino Recién Llegado a EE.UU.`,
    cover: `https://alexanderfigueredo.com/libros/manual-latino-recien-llegado.jpg`,
    spec: `Inmigración · PDF · ~110 págs`,
    grupo: `Inmigración`,
    price: 14.99,
    buyUrl: `https://buy.stripe.com/28E28l9DK2TtaI8by3d7q04`,
    desc: `Guía completa de supervivencia y éxito para empezar tu nueva vida en EE.UU. Paso a paso.`,
    specs: [`Documentos, vivienda, trabajo, crédito, salud`, `~110 páginas paso a paso`, `Escrito por médico exiliado cubano`],
  },
  {
    title: `La Vida del Latino en Estados Unidos`,
    cover: `https://alexanderfigueredo.com/libros/vida-del-latino-eeuu.jpg`,
    spec: `Inmigración · PDF · Libro completo`,
    grupo: `Inmigración`,
    price: 14.99,
    buyUrl: `https://buy.stripe.com/8x214heY4fGfeYoby3d7q0g`,
    desc: `La historia completa del latino en EE.UU.: trabajo, familia, cultura y los puentes entre dos mundos.`,
    specs: [`Crónica completa de la experiencia latina`, `Trabajo, familia, cultura, logros`, `También en Amazon (Kindle y tapa blanda)`],
  },
  {
    title: `Historias de Inmigrantes — Dolor, Fe, Trabajo`,
    cover: `https://alexanderfigueredo.com/libros/historias-de-inmigrantes.jpg`,
    spec: `Inmigración · PDF · ~82 págs`,
    grupo: `Inmigración`,
    price: 14.99,
    buyUrl: `https://buy.stripe.com/fZu6oB2bi9hR4jKdGbd7q0c`,
    desc: `La verdad que casi nadie cuenta sobre el sueño americano, escrita por un médico que cruzó el Darién.`,
    specs: [`28 relatos basados en la realidad`, `5 partes: dolor, fe, trabajo y reconstrucción`, `Escrito por médico que cruzó el Darién`, `Incluye recursos de ayuda gratuitos`],
  },
  {
    title: `Padres Latinos Criando Hijos Americanos`,
    cover: `https://alexanderfigueredo.com/libros/padres-latinos-hijos-americanos.jpg`,
    spec: `Inmigración · PDF · ~68 págs`,
    grupo: `Inmigración`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/cNicMZcPW1Pp03ucC7d7q0L`,
    desc: `Guía de crianza bicultural: honra tus raíces sin que tus hijos se queden atrás en su nuevo país.`,
    specs: [`Crianza bicultural práctica`, `Valores latinos + integración americana`, `Idioma, identidad y legado`],
  },
  {
    title: `Cómo Empezar de Cero en Otro País`,
    cover: `https://alexanderfigueredo.com/libros/empezar-cero-otro-pais.jpg`,
    spec: `Inmigración · PDF · Guía de reinvención`,
    grupo: `Inmigración`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/8x26oB8zG79Jg2s7hNd7q0e`,
    desc: `Nuevo país, nueva identidad: la guía de reinvención para quien llegó con una maleta y un sueño.`,
    specs: [`Nuevo trabajo, hogar e idioma`, `Guía de reinvención para inmigrantes`, `Llegaste con una maleta y un sueño`],
  },
  {
    title: `Choque Cultural, Soledad y Nostalgia`,
    cover: `https://alexanderfigueredo.com/libros/choque-cultural-soledad.jpg`,
    spec: `Inmigración · PDF · Guía de adaptación`,
    grupo: `Inmigración`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/8x29ANdU0gKjbMc0Tpd7q0i`,
    desc: `El lado emocional de la emigración que nadie habla. Cómo atravesarlo sin romperte.`,
    specs: [`El lado emocional de la emigración`, `Choque cultural, soledad y nostalgia`, `Construir paz interior en nueva tierra`],
  },
  {
    title: `Cómo Mantener Tu Identidad Sin Quedarte Estancado`,
    cover: `https://alexanderfigueredo.com/libros/como-mantener-tu-identidad.jpg`,
    spec: `Inmigración · PDF · Guía`,
    grupo: `Inmigración`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/cNi6oB6ryfGf4jKdGbd7q0z`,
    desc: `Guía bicultural para el latino en EE.UU.: ni borrarte para encajar ni congelarte en el pasado.`,
    specs: [`Identidad bicultural práctica`, `Honra tus raíces y crece`, `Aprovecha tu superpoder bilingüe`],
  },
  {
    title: `Cómo Proteger a tu Familia (Inmigrante, Exiliado o Recién Llegado)`,
    cover: `https://alexanderfigueredo.com/libros/proteger-familia-inmigrante.jpg`,
    spec: `Inmigración · PDF · Guía completa`,
    grupo: `Inmigración`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/dRm00d2bicu36rSgSnd7q0R`,
    desc: `Las 7 áreas de protección que toda familia inmigrante necesita. Conoce tus derechos.`,
    specs: [`7 áreas de protección`, `Documentos, derechos y tarjetas rojas`, `Salud, seguros y finanzas`],
  },
  {
    title: `Cómo Sobrevivir tu Primer Año en EE.UU.`,
    cover: `https://alexanderfigueredo.com/libros/como-sobrevivir-primer-ano-eeuu.jpg`,
    spec: `Inmigración · PDF · Guía`,
    grupo: `Inmigración`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/8x2bIVdU065FbMc6dJd7q0V`,
    desc: `De la supervivencia al éxito: tu hoja de ruta para que tu primer año en EE.UU. sea tu mejor inversión.`,
    specs: [`4 fases: supervivencia a éxito`, `SSN/ITIN, banco, trabajo, crédito`, `Echar raíces sin perderte`],
  },
  {
    title: `Manual: Warehouses, Cleaning, Caregiving, Construction, Delivery y Hospitality`,
    cover: `https://alexanderfigueredo.com/libros/manual-warehouses-cleaning.jpg`,
    spec: `Trabajo · PDF · Manual`,
    grupo: `Trabajo`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/bJebIVdU00Ll03u1Xtd7q0b`,
    desc: `Las 6 industrias que más contratan a hispanos sin inglés perfecto. Derechos, salario y crecimiento.`,
    specs: [`Las 6 industrias que más contratan hispanos`, `Cómo conseguir el trabajo en cada una`, `Cuánto se paga y cómo crecer`],
  },
  {
    title: `Cómo Conseguir Trabajo en Hospitales, Clínicas y Home Care`,
    cover: `https://alexanderfigueredo.com/libros/conseguir-trabajo-sector-salud.jpg`,
    spec: `Trabajo · PDF · Manual`,
    grupo: `Trabajo`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/dRm6oB17ealV17y31xd7q0A`,
    desc: `El sector salud nunca deja de contratar. Cómo entrar desde cero con o sin experiencia previa.`,
    specs: [`Hospital, clínica, nursing home, home care`, `Puestos de entrada y sueldos`, `Certis cortas y cómo destacar en entrevista`],
  },
  {
    title: `Cómo Buscar Trabajo en EE.UU. Sin Experiencia`,
    cover: `https://alexanderfigueredo.com/libros/buscar-trabajo-sin-experiencia.jpg`,
    spec: `Trabajo · PDF · Guía inicial`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/4gM5kxaHOeCb6rS1Xtd7q0d`,
    desc: `El mapa completo para empezar desde cero en EE.UU. sin experiencia previa.`,
    specs: [`Dónde buscar y cómo aplicar`, `Primera solicitud y entrevista`, `Conseguir el primer empleo desde cero`],
  },
  {
    title: `Cómo Funcionan los Staffing Agencies`,
    cover: `https://alexanderfigueredo.com/libros/staffing-agencies.jpg`,
    spec: `Trabajo · PDF · Guía`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/6oU5kx03a51B4jKgSnd7q0s`,
    desc: `La puerta de entrada al trabajo en EE.UU. para muchos hispanos. Todo sobre las agencias de staffing.`,
    specs: [`Qué son y cómo aplicar`, `Tus derechos en el staffing`, `Del temporal al empleo fijo`],
  },
  {
    title: `Cómo Hacer un Resume Americano`,
    cover: `https://alexanderfigueredo.com/libros/resume-americano.jpg`,
    spec: `Trabajo · PDF · Guía`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/6oUaERg289hRbMc59Fd7q0u`,
    desc: `El resume americano que sí consigue entrevistas. Aprende a describir tu experiencia correctamente.`,
    specs: [`Resume al estilo americano que consigue entrevistas`, `Qué incluir y qué dejar fuera`, `Errores que te descartan antes de leerte`],
  },
  {
    title: `Cómo Pasar de Trabajos Duros a Mejores Pagados`,
    cover: `https://alexanderfigueredo.com/libros/pasar-trabajos-mejor-pagados.jpg`,
    spec: `Trabajo · PDF · Guía`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/14AcMZ9DK79J6rScC7d7q0v`,
    desc: `El plan para salir de los trabajos físicos y dar el salto a empleos mejor pagados en EE.UU.`,
    specs: [`Habilidades que suman`, `Crecer dentro de tu industria`, `Sin arriesgar tu estabilidad`],
  },
  {
    title: `Qué Decir en una Entrevista de Trabajo`,
    cover: `https://alexanderfigueredo.com/libros/que-decir-entrevista-trabajo.jpg`,
    spec: `Trabajo · PDF · Guía`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/eVqeV73fmbpZ2bC59Fd7q0B`,
    desc: `Las palabras exactas que consiguen el empleo. Qué decir, qué evitar y cómo causar buena impresión.`,
    specs: [`Palabras exactas que consiguen el empleo`, `Cómo hablar de debilidades`, `Aunque tu inglés sea básico`],
  },
  {
    title: `Inglés Práctico Para el Trabajo`,
    cover: `https://alexanderfigueredo.com/libros/ingles-practico-trabajo.jpg`,
    spec: `Trabajo · PDF · Guía`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/cNi00d9DKdy76rS1Xtd7q0N`,
    desc: `Las frases de inglés que de verdad necesitas en tu turno para comunicarte y crecer.`,
    specs: [`30 frases del primer día`, `Vocabulario por industria`, `10 errores que más confunden`],
  },
  {
    title: `Derechos Básicos del Trabajador Inmigrante`,
    cover: `https://alexanderfigueredo.com/libros/derechos-basicos-trabajador-inmigrante.jpg`,
    spec: `Trabajo · PDF · Guía`,
    grupo: `Trabajo`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/14A4gtaHO2Tt5nO31xd7q0W`,
    desc: `Tus derechos en el trabajo en EE.UU. existen sin importar tu estatus migratorio. Conócelos.`,
    specs: [`Salario mínimo y horas extra`, `Lugar de trabajo seguro`, `Qué hacer ante el abuso o robo de salario`],
  },
  {
    title: `Manual Emocional del Exiliado`,
    cover: `https://alexanderfigueredo.com/libros/manual-emocional-exiliado.jpg`,
    spec: `Salud · PDF · Guía de sanación`,
    grupo: `Salud`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/3cI9AN4jqalV17y59Fd7q08`,
    desc: `Guía de sanación para quienes tuvieron que irse. Del exilio al renacer, escrito por un médico.`,
    specs: [`Del duelo y desarraigo a la esperanza`, `Escrito por médico que también se fue`, `También en Amazon`],
  },
  {
    title: `Cómo Funciona el Seguro Médico en EE.UU.`,
    cover: `https://alexanderfigueredo.com/libros/como-funciona-seguro-medico.jpg`,
    spec: `Salud · PDF · Manual`,
    grupo: `Salud`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/cNi8wJ5nu51B3fGfOjd7q0j`,
    desc: `El laberinto del seguro de salud en EE.UU. explicado claro. Elige bien y no te arruines.`,
    specs: [`Primas, deducibles, copagos explicados`, `HMO, PPO, EPO y HDHP`, `Mercado/ACA, Medicaid y Medicare`, `También en Amazon`],
  },
  {
    title: `Medicaid, Medicare, Obamacare y Seguros Privados — Explicado Fácil`,
    cover: `https://alexanderfigueredo.com/libros/medicaid-medicare-obamacare-seguros-privados.jpg`,
    spec: `Salud · PDF · Manual`,
    grupo: `Salud`,
    price: 7.99,
    buyUrl: `https://buy.stripe.com/dRm7sFbLS8dNdUk45Bd7q0x`,
    desc: `Los 4 caminos a la cobertura de salud en EE.UU., en español claro. Quién califica y cómo aplicar.`,
    specs: [`4 caminos al seguro de salud`, `HMO vs PPO explicado`, `Reglas para inmigrantes`],
  },
  {
    title: `Qué Hacer si No Tienes Seguro Médico`,
    cover: `https://alexanderfigueredo.com/libros/que-hacer-sin-seguro.jpg`,
    spec: `Salud · PDF · Guía de emergencia`,
    grupo: `Salud`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/4gM3cp5nubpZeYo9pVd7q0k`,
    desc: `Guía de emergencia: cómo acceder a atención médica en EE.UU. aunque no tengas seguro.`,
    specs: [`Clínicas gratuitas y centros comunitarios`, `Medicamentos a bajo costo`, `Acceder a atención sin seguro en EE.UU.`],
  },
  {
    title: `10 Cosas que Debes Saber Antes de Comprar Seguro Médico`,
    cover: `https://alexanderfigueredo.com/libros/10-cosas-antes-comprar-seguro-medico.jpg`,
    spec: `Salud · PDF · Guía rápida`,
    grupo: `Salud`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/14AfZb6rydy7dUk59Fd7q0H`,
    desc: `Las 10 claves para no comprar seguro médico a ciegas. En español claro.`,
    specs: [`Deducibles, coaseguros, redes y exclusiones`, `Cómo comparar y elegir bien`, `La letra pequeña que nadie te explica`],
  },
  {
    title: `Errores Comunes al Comprar Seguros`,
    cover: `https://alexanderfigueredo.com/libros/errores-comprar-seguros.jpg`,
    spec: `Salud · PDF · Guía`,
    grupo: `Salud`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/5kQaER8zG9hR7vW7hNd7q0M`,
    desc: `La forma correcta vs incorrecta de comprar seguros en EE.UU. La letra pequeña que nadie explica.`,
    specs: [`Prima, deducible, copago explicados`, `HMO, PPO y cuándo conviene cada uno`, `Plan de acción en 7 pasos`],
  },
  {
    title: `Cómo Leer una Factura Médica`,
    cover: `https://alexanderfigueredo.com/libros/leer-factura-medica.jpg`,
    spec: `Salud · PDF · Guía`,
    grupo: `Salud`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/14A4gt5nufGf7vWgSnd7q0Q`,
    desc: `Entiende y disputa cualquier factura del sistema de salud en EE.UU. y no pagues de más.`,
    specs: [`Anatomía de una factura médica`, `Por qué los errores son tan comunes`, `Cómo disputarla y no pagar de más`],
  },
  {
    title: `Qué Hacer si Recibes una Factura Médica`,
    cover: `https://alexanderfigueredo.com/libros/que-hacer-factura-medica.jpg`,
    spec: `Salud · PDF · Guía de acción`,
    grupo: `Salud`,
    price: 3.99,
    buyUrl: `https://buy.stripe.com/00weV7eY40LldUkatZd7q0U`,
    desc: `Tu guía de respuesta cuando llega la factura médica. Revisa, negocia y resuelve con calma.`,
    specs: [`Plan en 6 pasos inmediatos`, `Negociar y detectar errores`, `Pedir asistencia financiera`],
  },
]

export const LIBROS_GRUPOS: { key: string; label: string }[] = [
  { key: 'Finanzas', label: 'Crédito y finanzas' },
  { key: 'Inmigración', label: 'Vida del inmigrante' },
  { key: 'Trabajo', label: 'Trabajo y empleo' },
  { key: 'Salud', label: 'Seguros y salud' },
]
